repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: debug-statements

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        pass_filenames: false

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: python
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: pflake8
        language: python
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
