# Generated by Django 4.1.7 on 2023-04-08 23:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date and Time")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificatioin Date and Time")),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Porte pequeno"), ("M", "Porte Médio"), ("B", "Porte Grande")],
                        max_length=1,
                        verbose_name="Idade",
                    ),
                ),
                (
                    "age",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0.0)], verbose_name="Idade"
                    ),
                ),
                ("behavior", models.CharField(max_length=100, verbose_name="Comportamento")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("is_adopted", models.BooleanField(default=False, verbose_name="Addotado")),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pets", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
