# Generated by Django 4.1.7 on 2023-04-11 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pet", "0002_alter_pet_options_alter_pet_age_alter_pet_shelter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="is_adopted",
            field=models.BooleanField(default=False, verbose_name="Adotado"),
        ),
        migrations.CreateModel(
            name="Adoption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date and Time")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificatioin Date and Time")),
                ("date", models.DateField(verbose_name="Data")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("pet", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="pet.pet")),
                (
                    "tutor",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "is_shelter": False, "is_tutor": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
