# Generated by Django 4.1.7 on 2023-04-19 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0003_alter_pet_is_adopted_adoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="", verbose_name="Foto"),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="pet",
            field=models.OneToOneField(
                limit_choices_to={"is_active": True, "is_adopted": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="pet.pet",
            ),
        ),
    ]
