# Generated by Django 4.1.7 on 2023-04-19 02:03

from django.db import migrations, models

import adopet.pet.models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0004_pet_foto_alter_adoption_pet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="foto",
        ),
        migrations.AddField(
            model_name="pet",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=adopet.pet.models.upload_to, verbose_name="Foto"),
        ),
    ]
