# Generated by Django 4.1.7 on 2023-04-20 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pet", "0005_remove_pet_foto_pet_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="tutor",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "role": "T"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adoptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="shelter",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "role": "S"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
