# Generated by Django 4.1.7 on 2023-04-21 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import adopet.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date and Time")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificatioin Date and Time")),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Porte pequeno"), ("M", "Porte Médio"), ("B", "Porte Grande")],
                        max_length=1,
                        verbose_name="Porte",
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="Idade")),
                ("behavior", models.CharField(max_length=100, verbose_name="Comportamento")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=adopet.core.models.upload_to, verbose_name="Foto"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("is_adopted", models.BooleanField(default=False, verbose_name="Adotado")),
                (
                    "shelter",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "role": "S"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Adoption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation Date and Time")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="Modificatioin Date and Time")),
                ("date", models.DateField(verbose_name="Data")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "pet",
                    models.OneToOneField(
                        limit_choices_to={"is_active": True, "is_adopted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pet",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "role": "T"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
