# Generated by Django 4.1.7 on 2023-04-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_customuser_options_customuser_is_shelter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_shelter",
            field=models.BooleanField(default=False, verbose_name="Abrigo"),
        ),
    ]
