# Generated by Django 4.1.7 on 2023-04-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_customuser_is_shelter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_shelter",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_tutor",
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True, choices=[("T", "Tutor"), ("S", "Abrigo")], max_length=1, null=True, verbose_name="Cargos"
            ),
        ),
    ]
