services:

  app:
    container_name: adopet_api_app
    build:
      dockerfile: docker/Dockerfile.dev
      context: .
    image: adopet:latest
    volumes:
      - .:/app/
    restart: 'no'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://adopet_user:123456@database:5432/adopet_user
      - PYTHONBREAKPOINT=ipdb.set_trace
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    container_name: adopet_api_db
    image: postgres:15.1
    restart: 'no'
    volumes:
      - pg_datebase:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=adopet_user
    ports:
      - 5432:5432


volumes:
  pg_datebase:
