FROM python:3.11.2-slim-buster

ARG USER_DIR=/app

# set work directory
WORKDIR $USER_DIR

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Create the app user
RUN groupadd app && useradd -g app app

# install depedencies for postgres
RUN apt-get update && apt-get install -y\
    gcc\
    libpq-dev\
    && rm -rf /var/lib/apt/lists/*

# copy project
COPY requirements.txt requirements-dev.txt ./

# install dependencies
RUN set -ex && \
    pip install -U pip &&\
    pip install --no-cache-dir -r requirements.txt --no-deps &&\
    pip install --no-cache-dir -r requirements-dev.txt --no-deps &&\
    pip cache purge

COPY . .

RUN chown -R app:app $USER_DIR
USER app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
