# Generated by Django 4.1.7 on 2023-04-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="about",
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name="Sobre"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Telefone"),
        ),
    ]
